steps:
  # - name: "gcr.io/cloud-builders/docker"
  #   id: build-base-image
  #   args:
  #     ["build", 
  #     "--tag", 
  #     "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/base-image:${BUILD_ID}", 
  #     "--tag", 
  #     "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/base-image:latest", 
  #     "-f", 
  #     "Dockerfile.base", 
  #     "."]
  
  # - name: "gcr.io/cloud-builders/docker"
  #   id: push-base-image
  #   args:
  #     ["push",
  #     "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/base-image:${BUILD_ID}"]

  # - name: "gcr.io/cloud-builders/docker"
  #   id: push-base-image-latest
  #   args:
  #     ["push",
  #     "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/base-image:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: pull-base-image
    args:
      ["pull",
      "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/base-image:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: build-backend_v1-image
    args:
      ["build", 
      "--tag", 
      "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/backend_v1:${BUILD_ID}",
      "--tag", 
      "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/backend_v1:latest", 
      "--build-arg",
      "BASE_IMAGE_URI=northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/base-image:latest",
      "--build-arg",
      "SERVING_PORT=8080",
      "-f", 
      "Dockerfile.backend_v1", 
      "."]
  
  - name: "gcr.io/cloud-builders/docker"
    id: push-backend_v1-image
    args:
      ["push",
      "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/backend_v1:${BUILD_ID}"]

  - name: "gcr.io/cloud-builders/docker"
    id: push-backend_v1-image-latest
    args:
      ["push",
      "northamerica-northeast1-docker.pkg.dev/ift6758-hw5-405618/ift6758-hw5/backend_v1:latest"]
